<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Phalcon PHP Framework</title>
        <link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->url->get('img/favicon.ico')?>"/>
    </head>
    <body>
        <h1>Congratulations!</h1>
        <p>You're now flying with Phalcon. Great things are about to happen!</p>
        <p>This page is located at <code>views/index.phtml</code></p>
    </body>
</html>
